### ISSUE TITLE
When running command add --htri-only encount this problem

### ISSUE THREAD

**Issue by swg209** [jiyanggao/Video-Person-ReID#21]
When I run the command :  python main_video_person_reid.py --htri-only
got the error below. Could you please help  me out?
```
 File "/home/swg/Re-id/Video_Person_Reid/losses.py", line 81, in forward
    dist_ap = torch.cat(dist_ap)
RuntimeError: zero-dimensional tensor (at position 0) cannot be concatenated
``

**Comment by swg209** [comment]
I found that this problem is cause by pytorch version.  when I change torch.cat to torch.stack solve the problem.

**Comment by DNHanXu** [comment]
hi @swg209. Which version of pytorch did you use? And did you encounter GPU out of memory problem while testing process?

**Comment by swg209** [comment]
I use pytorch1.0 , python3.6. When testing ,it will need much more GPU memory.  But I didn't encount this.
I use K80 ,11GB.

**Comment by DNHanXu** [comment]
i used 1080ti with 11GB memory but still have ‘out of memory’ problem when testing, which is quite confusing...

**Comment by DNHanXu** [comment]
@swg209 did you work with K80/11GB without any other changes on codes? What is your CPU memory by the way?
