### ISSUE TITLE
GPU Out of Memory

### ISSUE THREAD

**Issue by DNHanXu** [jiyanggao/Video-Person-ReID#22]
I made some changes on original codes to make it compatible with torch 1.0.1 and python 3.6. However, I encounter **gpu out of memory problem during testing process**. Does anyone have the same problem? And is it caused by version difference? I used 1080ti with 11GB memory.

**Comment by DNHanXu** [comment]
make some changes according to version update of Pytorch from 0.3 to 0.4 will solve this problem

**Comment by usename6** [comment]
I had same problem,could you tell me how to solve it?

**Comment by DNHanXu** [comment]
For torch >= 0.4, try to use 'torch.no_grad()' instead of 'volatile' flag

**Comment by DNHanXu** [comment]
> I had same problem,could you tell me how to solve it?

For torch >= 0.4, try to use 'torch.no_grad()' instead of 'volatile' flag.

**Comment by DNHanXu** [comment]
@usename6 For torch >= 0.4, try to use 'torch.no_grad()' instead of 'volatile' flag.
