### ISSUE TITLE
out of memory problem

### ISSUE THREAD

**Issue by Fungungun** [jiyanggao/Video-Person-ReID#5]
Hi,

Thanks for your work. I got out of memory problem during test. I then printed out the shapes of images and found that it crashed when I got imgs.shape=[65, 4, 3, .., ..] and it seems like I need to process 65 * 4 images on the GPU card in one shot. I guess this is  a problem even I've got 12GB GPU memory.

So I am wondering how you deal with this problem? Did you just use a gpu card with enough memory or you did anything else? Please let me know and much appreciate your work.

Update:
I was using torch 0.4 , python 3.6. I have switched to torch 0.3 and python 2.7 and so far it works fine. 

Thanks.

**Comment by lzj322** [comment]
@Fungungun I swtiched to torch 0.3.1 and python 2.7.13 as author said, but I still got out of memory problem. I have 12GB GPU memory.

**Comment by DNHanXu** [comment]
Hi, @Fungungun. I encounter the same out of memory problem here. The images shape could be [220, 4, 3, ...] or larger. How do you solve the problem and do you think version changing can really solve the problem?

**Comment by hopstone** [comment]
@Fungungun I have the same problem. Would you please share with me how to resolve if you had fixed it?  I've tried to modify following code in main_video_person_reid.py, but 'out of memory' problem still exists.  I'm using torch 1.1.0, python 3.6.9.  Thanks a lot.
imgs = Variable(imgs, volatile=True)    -->
with torch.no_grad():
            imgs = Variable(imgs)
